# Editor Config
theme = "catppuccin_mocha"

[editor]
cursorline = true
true-color = true
color-modes = true
auto-pairs = false
scrolloff = 0
scroll-lines = 3

[editor.statusline]
left = [ "mode", "file-name", ]
center = [ "spinner", ]
right = [
  "position", "position-percentage", "diagnostics",
  "selections", "file-encoding", "file-line-ending",
  "file-type", ]
separator = "│"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "block"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = false
character = "│"

# Key Remapping
[keys.normal]
"\\"."c"."o" = [ ":config-open", ]
"\\"."c"."r" = [ ":config-reload", ]
"esc" = [ "keep_primary_selection", "normal_mode", ]
"C-s" = [ ":wa", ]
"C-q"."q" = [ ":xa", ]
"C-q"."b" = [ ":w", ":bc", ]
"C-e" = [ "scroll_down", ]
"C-y" = [ "scroll_up", ]
"C-r" = [ "redo", ]
"C-j" = [ "move_line_down", "align_view_center", ]
"C-k" = [ "move_line_up", "align_view_center", ]
"C-a" = [ "select_all", "select_mode", ]
"$" = [ "goto_line_end", ]
"^" = [ "goto_first_nonwhitespace", ]
"0" = [ "goto_line_start", ]
"G" = [ "goto_last_line", ]
"M" = [ "goto_window_center", ]
"V" = [ "extend_to_line_bounds", "select_mode", ]
"D" = [
  "select_mode", "goto_line_end",
  "yank_main_selection_to_clipboard", "delete_selection_noyank", ]
"x" = [ "yank_main_selection_to_clipboard", "delete_selection_noyank", ]
"d"."d" = [
  "extend_to_line_bounds", "yank_main_selection_to_clipboard",
  "delete_selection_noyank", ]
"d"."i"."w" = [
  "move_prev_word_start", "move_next_word_end",
  "yank_main_selection_to_clipboard", "delete_selection_noyank", ]
"t" = [ "yank_main_selection_to_clipboard", ]
"y"."y" = [ "extend_to_line_bounds", "yank_main_selection_to_clipboard", ]
"y"."i"."w" = [
  "move_prev_word_start", "move_next_word_end",
  "yank_main_selection_to_clipboard", ]
"s" = [
  "yank_main_selection_to_clipboard", "delete_selection_noyank",
  "insert_mode", ]
"c"."c" = [
  "extend_to_line_bounds", "yank_main_selection_to_clipboard",
  "delete_selection_noyank", "open_above", ]
"c"."i"."w" = [
  "move_prev_word_start", "move_next_word_end",
  "yank_main_selection_to_clipboard", "delete_selection_noyank",
  "insert_mode", ]
"?" = [ "select_regex", ]
"p" = [ "paste_clipboard_after", ]
"P" = [ "paste_clipboard_before", ]

[keys.select]
"\\"."c"."o" = [ ":config-open", ]
"\\"."c"."r" = [ ":config-reload", ]
"esc" = [ "keep_primary_selection", "normal_mode", ]
"tab" = [ "indent", ]
"S-tab" = [ "unindent", ]
"C-s" = [ ":wa", ]
"C-q"."q" = [ ":xa", ]
"C-q"."b" = [ ":w", ":bc", ]
"C-e" = [ "scroll_down", ]
"C-y" = [ "scroll_up", ]
"C-r" = [ "redo", "normal_mode", ]
# Helix doesn't support line move?
# C-j = [
#   "extend_to_line_bounds", "delete_selection", "paste_after",
#   "move_line_down", "select_mode", "goto_last_modification",
#   "move_char_left", ]
# C-k = [
#   "extend_to_line_bounds", "delete_selection", "move_line_up",
#   "move_line_up", "paste_after", "move_line_down",
#   "select_mode", "goto_last_modification", "move_char_left", ]
"$" = [ "goto_line_end", ]
"^" = [ "goto_first_nonwhitespace", ]
"0" = [ "goto_line_start", ]
"G" = [ "goto_last_line", ]
"M" = [ "goto_window_center", ]
"V" = [ "extend_to_line_bounds", "select_mode", ]
"x" = [ "yank_main_selection_to_clipboard", "delete_selection_noyank", ]
"d"."d" = [
  "extend_to_line_bounds", "yank_main_selection_to_clipboard",
  "delete_selection_noyank", ]
"t" = [ "yank_main_selection_to_clipboard", "normal_mode", ]
"y"."y" = [
  "extend_to_line_bounds", "yank_main_selection_to_clipboard",
  "normal_mode", ]
"s" = [ "yank_main_selection_to_clipboard", "delete_selection_noyank",
  "insert_mode", ]
"c"."c" = [
  "extend_to_line_bounds", "yank_main_selection_to_clipboard",
  "delete_selection_noyank", "open_above", ]
"?" = [ "select_regex", ]
"p" = [ "paste_clipboard_before", "delete_selection_noyank", ]
"P" = [
  "paste_clipboard_before", "yank_main_selection_to_clipboard",
  "delete_selection_noyank", ]

[keys.insert]
"esc" = [ "keep_primary_selection", "normal_mode", ]

# If copy/paste doesn't work properly, install xclip.
