# Editor Config
# theme = "catppuccin_frappe"
theme = "everforest_dark"

[editor]
cursorline = true
cursorcolumn = false
true-color = true
color-modes = true
auto-pairs = false
auto-save = false
scrolloff = 0
scroll-lines = 3
bufferline = "always"

[editor.statusline]
left = [ "mode", "file-name", ]
center = [ "spinner", ]
right = [
  "position", "position-percentage", "diagnostics",
  "selections", "file-encoding", "file-line-ending",
  "file-type", ]
separator = "│"
mode.normal = "NORMAL"
mode.select = "SELECT"
mode.insert = "INSERT"

[editor.lsp]
display-messages = true

# [editor.cursor-shape]
# insert = "underline"
# normal = "underline"
# select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = false
character = "│"

# Key Remapping
[keys.normal]
"\\"."c"."o" = [ ":config-open", ]
"\\"."c"."r" = [ ":config-reload", ]
"esc" = [ "keep_primary_selection", "normal_mode", ]
"C-s" = [ ":wa", ]
"C-q"."q" = [ ":xa", ]
"C-q"."b" = [ ":w", ":bc", ]
"C-q"."w" = [ ":w", "wclose", ]
"C-e" = [ "scroll_down", ]
"C-y" = [ "scroll_up", ]
"C-r" = [ "redo", ]
"C-j" = [ "move_line_down", "align_view_center", ]
"C-k" = [ "move_line_up", "align_view_center", ]
"C-a" = [ "select_all", "select_mode", ]
"$" = [ "goto_line_end", ]
"^" = [ "goto_first_nonwhitespace", ]
"0" = [ "goto_line_start", ]
"G" = [ "goto_last_line", ]
"M" = [ "goto_window_center", ]
"V" = [ "extend_to_line_bounds", "select_mode", ]
"D" = [
  "select_mode", "goto_line_end",
  "yank_main_selection_to_clipboard", "delete_selection_noyank", ]
"x" = [ "yank_main_selection_to_clipboard", "delete_selection_noyank", ]
"d"."d" = [
  "extend_to_line_bounds", "yank_main_selection_to_clipboard",
  "delete_selection_noyank", ]
"d"."i"."w" = [
  "move_char_right", "move_prev_word_start", "move_next_word_end",
  "yank_main_selection_to_clipboard", "delete_selection_noyank", ]
"t" = [ "yank_main_selection_to_clipboard", ]
"y"."y" = [ "extend_to_line_bounds", "yank_main_selection_to_clipboard", ]
"y"."i"."w" = [
  "move_char_right", "move_prev_word_start", "move_next_word_end",
  "yank_main_selection_to_clipboard", ]
"s" = [
  "yank_main_selection_to_clipboard", "delete_selection_noyank",
  "insert_mode", ]
"c"."c" = [
  "extend_to_line_bounds", "yank_main_selection_to_clipboard",
  "delete_selection_noyank", "open_above", ]
"c"."i"."w" = [
  "move_char_right", "move_prev_word_start", "move_next_word_end",
  "yank_main_selection_to_clipboard", "delete_selection_noyank",
  "insert_mode", ]
"?" = [ "select_regex", ]
"p" = [ "paste_clipboard_after", ]
"P" = [ "paste_clipboard_before", ]

[keys.select]
"\\"."c"."o" = [ ":config-open", ]
"\\"."c"."r" = [ ":config-reload", ]
"esc" = [ "keep_primary_selection", "normal_mode", ]
"tab" = [ "extend_to_line_bounds", "indent", ]
"S-tab" = [ "extend_to_line_bounds", "unindent", ]
"C-s" = [ ":wa", ]
"C-q"."q" = [ ":xa", ]
"C-q"."b" = [ ":w", ":bc", ]
"C-q"."w" = [ ":w", "wclose", ]
"C-e" = [ "scroll_down", ]
"C-y" = [ "scroll_up", ]
"C-r" = [ "redo", "normal_mode", ]
"C-j" = [
  "ensure_selections_forward", "extend_to_line_bounds",
  "extend_char_right", "extend_char_left", "delete_selection",
  "add_newline_below", "move_line_down", "replace_with_yanked",
  "select_mode", ]
"C-k" = [
  "ensure_selections_forward", "extend_to_line_bounds",
  "extend_char_right", "extend_char_left", "delete_selection",
  "move_line_up", "add_newline_above", "move_line_up",
  "replace_with_yanked", "select_mode", ]
# "H" = [ "select_mode", "move_char_left", "extend_to_line_bounds", ]
# "J" = [ "select_mode", "move_line_down", "extend_to_line_bounds", ]
# "K" = [ "select_mode", "move_line_up", "extend_to_line_bounds", ]
# "L" = [ "select_mode", "move_char_right", "extend_to_line_bounds", ]
"$" = [ "goto_line_end", ]
"^" = [ "goto_first_nonwhitespace", ]
"0" = [ "goto_line_start", ]
"G" = [ "goto_last_line", ]
"M" = [ "goto_window_center", ]
"V" = [ "extend_to_line_bounds", "select_mode", ]
"x" = [ "yank_main_selection_to_clipboard", "delete_selection_noyank", ]
"d"."d" = [
  "extend_to_line_bounds", "yank_main_selection_to_clipboard",
  "delete_selection_noyank", ]
"t" = [ "yank_main_selection_to_clipboard", "normal_mode", ]
"y"."y" = [
  "extend_to_line_bounds", "yank_main_selection_to_clipboard",
  "normal_mode", ]
"s" = [
  "yank_main_selection_to_clipboard", "delete_selection_noyank",
  "insert_mode", ]
"c"."c" = [
  "extend_to_line_bounds", "yank_main_selection_to_clipboard",
  "delete_selection_noyank", "open_above", ]
"?" = [ "select_regex", ]
"p" = [ "paste_clipboard_before", "delete_selection_noyank", ]
"P" = [
  "paste_clipboard_before", "yank_main_selection_to_clipboard",
  "delete_selection_noyank", ]

[keys.insert]
"esc" = [ "keep_primary_selection", "normal_mode", ]

# If copy/paste doesn't work properly, install xclip.
